export default {
  FETCH_TEXT: "FETCH_TEXT",

  AUTO_LOGIN: "AUTO_LOGIN",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  FOLLOWUP_USER: "FOLLOWUP_USER",
  AUTH_ERROR: "AUTH_ERROR",

  FETCH_LIST: "FETCH_LIST",
  CLEAR_LIST: "CLEAR_LIST",

  EDIT_PROFILE: "EDIT_PROFILE",

  UPDATE_TO_USER_INFO: "UPDATE_TO_USER_INFO",
  CLEAR_TO_USER_INFO: "CLEAR_TO_USER_INFO",
  MSG_RECEIVED: "MSG_RECEIVED",
  GET_MSG_LIST: "GET_MSG_LIST",
  SUB_TO_MSG: "SUB_TO_MSG",
  UNSUB_TO_MSG: "UNSUB_TO_MSG",
  MSG_ERROR: "MSG_ERROR"
};
