export default {
  FETCH_TEXT: "FETCH_TEXT",

  AUTO_LOGIN: "AUTO_LOGIN",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  FOLLOWUP_USER: "FOLLOWUP_USER",
  AUTH_ERROR: "AUTH_ERROR",

  FETCH_LIST: "FETCH_LIST",

  EDIT_PROFILE: "EDIT_PROFILE",

  SEND_MSG: "SEND_MSG",
  GET_MSG: "GET_MSG",
  MSG_ERROR: "MSG_ERROR"
};
